# Configuration file for running speed test
# Dimension to test speed as a function of (n_bands, n_pixels, n_lines)
TEST_DIMENSION: "n_bands"

# Dimension sizes for generated hyperspectral image dataset
N_PIXELS: [500]
N_LINES: [3000]
N_BANDS: [10, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 100, 125, 150, 200]

# General detector params
N_REPEATS: 5

# Define models to include in test and their parameters
erx:
  include: True
  buffer_len: 99
  projected_dimensions: 5
  momentum: 0.1
  line_offset: 0
  normalise_md: False
  threshold: null

rx_baseline:
  include: True
  buffer_len: 99
  normalise_md: False
  threshold: null

lbl_ad:
  include: True
  buffer_len: 99
  pca_dims: 3
  normalise_md: False
  threshold: null
  auto_threshold: False

rt_ck_rxd:
  include: True
  buffer_len: 99
  normalise_md: False
  threshold: null

rx_bil:
  include: True
  buffer_len: 99
  pixel_dropout: 0.5
  normalise_md: False
  threshold: null

cdlss_ad:
  include: False
  buffer_len: 99
  normalise_md: False
  threshold: null