# Configuration file for running speed test
# Dataset directory for testing
HSI_DIR: "data/beach_dataset/beach_hsi.npy"
MASK_DIR: "data/beach_dataset/beach_mask.npy"
REVERSE: False

# General detector params
N_REPEATS: 1

# Skip metrics calculation in show results
SKIP_METRICS: False
SHOW_STD_ON_ROC: True

# ERX Params
BUFFER_LEN: 99
DIMENSION_LIST: [1, 1, 3, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, null]
MOMENTUM: 0.1
LINE_OFFSET: 0
NORMALISE_MD: True
THRESHOLD: 5

# General speed test params
RUN_SPEED_TEST: False
N_PIXELS: 500
N_LINES: 3000
N_BANDS: 200
SPEED_DIMENSION_LIST: [1, 1, 3, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 125, 150, null]
